### PR TITLE
Include new installation methods

### PR DESCRIPTION
**Pull request by CompeyDev**
The docs are now updated to include all the current methods of install lune. These include:

* Homebrew (`brew install lune`)
* APT (`sudo apt install lune`)
* AppImage (Downloading the latest image)

### CODE REVIEW

**Comment by jackprogramsjp** [comment]
This PR removes the ability for me to add a commit history in part of my contributor role. I understand that this is the docs but I'd heavily appreciate it if I'm at least a part of a commit as I took time to establish the package into Homebrew. I thought you can suggest it on my PR but you just made your own PR and then just reworded some things based on mine I guess.

**Comment by CompeyDev** [comment]
I'll add you as a contributor to my fork, you can make changes to that as you'd like - that way you get the contributor role.

**Review by filiptibell — CHANGES_REQUESTED** [review]
Thanks for the PR! A couple things:

- Could you rebase this against main and remove the `pnpm` lockfile? This repo uses just plain `npm` and that lockfile
- I'm hesitant to add external urls like these for signing and installing using `apt` to the official docs, users will not be familiar with this host, but maybe we could host them on an official lune domain when we have that instead

**Comment by CompeyDev** [comment]
> Could you rebase this against main and remove the `pnpm` lockfile? This repo uses just plain `npm` and that lockfile
> 

I'll fix the merge conflicts soon.

> I'm hesitant to add external urls like these for signing and installing using `apt` to the official docs, users will not be familiar with this host, but maybe we could host them on an official lune domain when we have that instead.

It's way more convenient for me to use my already public shared repositories for packaging purposes (because I own the domain and can fix DNS/TLS issues, etc. among other reasons).

**Comment by CompeyDev** [comment]
Fixed the merge conflicts as discussed above.

**Comment by filiptibell** [comment]
@CompeyDev 

I'm guessing there's no way we can host the apt package on github along with everything else? I think some level of trust from users is needed and either hosting on github or a domain they can verify to be owned by the lune org builds some of that. I personally would be fine with using your apt package but have a feeling others may be (reasonably) skeptical.

Let me know if there's any other way forward with that, otherwise I think we should go with just the AppImage for now on the public docs (but feel free to keep the apt package in your repo)

**Comment by CompeyDev** [comment]
Technically it would be possible to host it on lune's github org, just that it would be quite inconvenient for me to host it and update cryptography things...

> Let me know if there's any other way forward with that, otherwise I think we should go with just the AppImage for now on the public docs (but feel free to keep the apt package in your repo)

This sounds reasonable; I guess we could add a section saying "this APT repo is not endorsed by or affilated with lune" and link the APT packages in the repo instead.

**Comment by CompeyDev** [comment]
> Technically it would be possible to host it on lune's github org, just that it would be quite inconvenient for me to host it and update cryptography things...
> 
> > Let me know if there's any other way forward with that, otherwise I think we should go with just the AppImage for now on the public docs (but feel free to keep the apt package in your repo)
> 
> This sounds reasonable; I guess we could add a section saying "this APT repo is not endorsed by or affilated with lune" and link the APT packages in the repo instead.

@filiptibell Bumping this - does this sound alright?

**Comment by filiptibell** [comment]
> @filiptibell Bumping this - does this sound alright?

> we could add a section saying "this APT repo is not endorsed by or affilated with lune" and link the APT packages in the repo instead

I think a disclaimer like that + something along the lines of "follow the instructions in this github repo (link)" sounds good, yeah

**Comment by CompeyDev** [comment]
> > @filiptibell Bumping this - does this sound alright?
> 
> > we could add a section saying "this APT repo is not endorsed by or affilated with lune" and link the APT packages in the repo instead
> 
> I think a disclaimer like that + something along the lines of "follow the instructions in this github repo (link)" sounds good, yeah

Great, I'll do that once I'm back from work!

**Review by filiptibell — APPROVED** [review]
Thank you!

**Pull request merged**
