### PR TITLE
Add DateTime properties

### PR DESCRIPTION
**Pull request by EliTheGingerCat**
Fixes https://github.com/lune-org/lune/issues/227.

### CODE REVIEW

**Comment by CompeyDev** [comment]
I don't think these are supposed to be manually added to api-references. API references are generated from moonwave doc comments, and are not intended to be manually edited.

The fix would involve extracting the fields within the `DateTime` table [here](https://github.com/lune-org/lune/blob/1d4d1635eba6a29fc06c821ad2fff24fe83df6f8/types/datetime.luau#L90-L95) in the generator script, located in the `.lune/` directory of this repository.

**Comment by EliTheGingerCat** [comment]
So should I make another pull request on the main repository, then use the extractor on this repository but change the URL to point to the branch on my copy of the main repository, and commit new changes to this pull request, if any?

**Comment by CompeyDev** [comment]
No, you'd just need to make a pull request on this repository, editing the generator to use the JSON fields for the properties.

**Comment by EliTheGingerCat** [comment]
I think this pull request can be closed since the documentation will be fixed the next time it is generated now that the Moonwave comments are correct.

**Pull request closed without merging**
